name: Plugin Issue Default Template
description: Bug Report or Feature Request, etc.
title: "[Plugin Name] "
body:
  - type: markdown
    id: notice
    attributes:
      value: |
        Please input your plugin name in the title.

        请在标题中输入插件名。
  - type: input
    id: plugin-name
    attributes:
      label: Plugin Name | 插件名
      description: Plugin Name, ex. `Auto Cleaner Re`
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description | 描述
      description: A clear and precise description of your issue.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots丨截图
      description: If applicable.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information | 附加信息
      description: If applicable.
    validations:
      required: false
